# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d03e6e12f6aade4fe43ce15e2cc7503a8ff768b5f28fc31d07fed372703bb339196130a609dd54524b2b945c257fbb2373b9b4f8045f2c09a0a17ff78cb607c7

test:
  secret_key_base: c0ebee8246f4e768d7bf82673a9a0802f5a7abe0837c3113f3a067bb2cb0bd49b2360f69907b1ad987c8bd32a0ab8340a8ba3875c26bf13dfcdcae9ddd4b5793

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
